+var data=[
    {
        "id":1,
        "team":"csk",
        "match":0,
        "win":0,
        "loss":0,
        "tie":0,
        "noresult":0
    },
    {
        "id":2,
        "team":"mi",
        "match":0,
        "win":0,
        "loss":0,
        "tie":0,
        "noresult":0
    },
    {
        "id":3,
        "team":"rcb",
        "match":0,
        "win":0,
        "loss":0,
        "tie":0,
        "noresult":0
    },
    {
        "id":4,
        "team":"kkr",
        "match":0,
        "win":0,
        "loss":0,
        "tie":0,
        "noresult":0
    },
    {
        "id":5,
        "team":"srh",
        "match":0,
        "win":0,
        "loss":0,
        "tie":0,
        "noresult":0
    },
    {
        "id":6,
        "team":"dc",
        "match":0,
        "win":0,
        "loss":0,
        "tie":0,
        "noresult":0
    },
    {
        "id":7,
        "team":"pk",
        "match":0,
        "win":0,
        "loss":0,
        "tie":0,
        "noresult":0
    },
    {
        "id":8,
        "team":"rr",
        "match":0,
        "win":0,
        "loss":0,
        "tie":0,
        "noresult":0
    }
]
 var a=JSON.stringify(data);
localStorage.setItem("point_table",a);

